added config and fixed variables

diff --git a/bin/chkpower b/bin/chkpower
--- a/bin/chkpower
+++ b/bin/chkpower
@@ -3,10 +3,19 @@
 # chkpower - Verify that servers are up and have been up for a bit.
 # Owner: Carl Schelin
 
-RUNBY=`/usr/xpg4/bin/id -u`
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 PROGNAME="chkpower"
-LOC=/usr/local/admin
-WHOCARES="carl.schelin@intrado.com paul.pietras@intrado.com"
 
 if [[ ! $RUNBY -eq 5000 ]]
 then
@@ -30,15 +39,15 @@ echo $$ > /var/tmp/$PROGNAME.pid
 # check to see if the server passed exists in the server listing or if it equals '[A|a]ll', otherwise exit without error
 if [[ -z $1 ]]
 then
-  SERVERLIST=`grep -v "^#" $LOC/etc/powerlist`
+  SERVERLIST=`grep -v "^#" ${SCRIPTS_ETC}/powerlist`
   SINGLESERVER="no"
 else
   if [[ $1 = "all" || $1 = "All" || $1 = "ALL" ]]
   then
-    SERVERLIST=`grep -v "^#" $LOC/etc/powerlist`
+    SERVERLIST=`grep -v "^#" ${SCRIPTS_ETC}/powerlist`
     SINGLESERVER="no"
   else
-    /usr/bin/grep -i "^${1}:" $LOC/etc/powerlist > /dev/null
+    /usr/bin/grep -i "^${1}:" ${SCRIPTS_ETC}/powerlist > /dev/null
     if [[ $? -ne 0 ]]
     then
       exit 0
@@ -62,7 +71,7 @@ do
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${SCRIPTS}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
@@ -151,9 +160,9 @@ then
   if [[ $SINGLESERVER = "yes" ]]
   then
     echo "$SERVERLIST was successfully contacted" | /usr/bin/tee $MAIL
-    if [[ -f $LOC/servers/$SERVERLIST/uptime.output ]]
+    if [[ -f ${SCRIPTS}/servers/$SERVERLIST/uptime.output ]]
     then
-      cat $LOC/servers/$SERVERLIST/uptime.output | /usr/bin/tee -a $MAIL
+      cat ${SCRIPTS}/servers/$SERVERLIST/uptime.output | /usr/bin/tee -a $MAIL
     else
       echo "WARNING: The unixsvc account was able to access the server but unable to run the uptime command. History shows the unixsvc account has been disabled. Please investigate." | /usr/bin/tee -a $MAIL
     fi
