updated to get the unixsuite files if the intrado files don't exist

diff --git a/bin/getetc b/bin/getetc
--- a/bin/getetc
+++ b/bin/getetc
@@ -73,6 +73,43 @@ do
     fi
   fi
 
+# perhaps the files are in the unixsuite directory
+  if [[ ! -f $SVRPATH/$CONTENT ]]
+  then
+    /usr/bin/scp $SERVER$FQDN:/opt/unixsuite/$CONTENT $SVRPATH/ 2>&1 &
+    PID=$!
+
+# wait for the specified number of seconds for scp to complete
+# if the timeout is exceeded, kill the process and move on to the next box
+
+# .2 seems to pause enough for the scp command to finish without taking a full second for each system.
+    /usr/bin/perl -e 'select(undef,undef,undef,.2)'
+    /usr/bin/ps -p $PID > /dev/null 2>&1
+    if [[ $? -eq 0 ]]
+    then
+      while [[ $TIMEOUT -gt 0 ]]
+      do
+        /usr/bin/ps -p $PID > /dev/null 2>&1
+        if [[ $? -ne 0 ]]
+        then
+          break
+        fi
+        TIMEOUT=$(($TIMEOUT - 1))
+        sleep 1
+      done
+
+# if the timeout reaches 0, then the process was killed. Report something.
+      if [[ $TIMEOUT -le 0 ]]
+      then
+        echo "ERROR: Unable to connect to server ($PROGNAME)" >> $SVRPATH/config.status
+        echo "ERROR: Unable to connect to server ($PROGNAME)" >> $SVRPATH/morning.status
+        chmod 664 $SVRPATH/config.status
+        chmod 664 $SVRPATH/morning.status
+        kill -KILL $PID
+      fi
+    fi
+  fi
+
 done
 
 exit 0
