updated ot use .config file

diff --git a/bin/getif b/bin/getif
--- a/bin/getif
+++ b/bin/getif
@@ -4,10 +4,27 @@
 # Owner: Carl Schelin
 # 8/15/11 - retrieve data from /opt/intrado/etc. change timeout to 180 seconds
 
-PROGNAME="getif"
-LOC=/usr/local/admin
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
 
-for i in `grep -v "^#" $LOC/etc/servers`
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! ${RUNBY} -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
+
+PROGNAME="getif"
+
+for i in `grep -v "^#" ${ADMIN_DATA}/servers`
 do
   SERVER=`echo $i|cut -f1 -d:`
   OS=`echo $i|cut -f3 -d:`
@@ -15,7 +32,7 @@ do
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${ADMIN}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
@@ -34,7 +51,7 @@ do
     rm $SVRPATH/$CONTENT.output
   fi
 
-  /usr/bin/scp $SERVER:/opt/intrado/etc/$CONTENT.output $SVRPATH 2>&1 &
+  /usr/bin/scp ${SERVER}:${SCRIPTS_LOGS}/${CONTENT}.output $SVRPATH 2>&1 &
   PID=$!
 
 # wait for the specified number of seconds for scp to complete
@@ -95,14 +112,6 @@ do
       then
         /usr/bin/mv $SVRPATH/$CONTENT.output $SVRPATH/$CONTENT.output.linux
         /usr/bin/egrep -v "(RX|TX) (packets|bytes)" $SVRPATH/$CONTENT.output.linux > $SVRPATH/$CONTENT.output
-      fi
-
-# tru64 records a bunch of stats in the output of ifconfig so need to filter those out to get a clean diff.
-      if [[ $OS = "OSF1" ]]
-      then
-        /usr/bin/mv $SVRPATH/$CONTENT.output $SVRPATH/$CONTENT.output.tru64
-        /usr/bin/egrep -v "est_(seconds|bytesent|bloksent|bytercvd|blokrcvd|mbytercvd|mbytesent|mblokrcvd|mbloksent|carrierfail|sendfail)" $SVRPATH/$CONTENT.output.tru64 > $SVRPATH/$CONTENT.output
-
       fi
 
 # now process the output files as normal
