updated to use .config

diff --git a/bin/getmpathd b/bin/getmpathd
--- a/bin/getmpathd
+++ b/bin/getmpathd
@@ -3,17 +3,34 @@
 # getmpathd - Retrieve the mpathd configurations
 # Owner: Carl Schelin
 
-PROGNAME="getmpathd"
-LOC=/usr/local/admin
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
 
-for i in `/usr/bin/grep -v "^#" $LOC/etc/servers | /usr/bin/grep SunOS`
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! $RUNBY -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
+
+PROGNAME="getmpathd"
+
+for i in `/usr/bin/grep -v "^#" ${ADMIN_DATA}/servers | /usr/bin/grep SunOS`
 do
   SERVER=`echo $i|cut -f1 -d:`
 
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${ADMIN}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
