Updated to use the .config file

diff --git a/bin/getservices b/bin/getservices
--- a/bin/getservices
+++ b/bin/getservices
@@ -1,9 +1,28 @@
 #!/bin/ksh
 
 # So pass the three letter code to this script for when to gather data.
-LOC=/usr/local/admin
 
-for i in `grep -v "^#" $LOC/etc/servers`
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! $RUNBY -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
+
+PROGNAME="getservices"
+
+for i in `grep -v "^#" ${ADMIN_DATA}/servers`
 do
   SERVER=`echo $i | cut -f1 -d:`
   OS=`echo $i | cut -f3 -d:`
@@ -12,19 +31,19 @@ do
 
   echo $SERVER
 
-  if [[ ! -d $LOC/servers/$SERVER ]]
+  if [[ ! -d ${ADMIN}/servers/$SERVER ]]
   then
-    mkdir $LOC/servers/$SERVER
+    mkdir ${ADMIN}/servers/$SERVER
   fi
 
   if [[ $OS = "Linux" ]]
   then
-    /usr/bin/ssh $SERVER "/sbin/chkconfig --list" | grep ":on	" | sort > $LOC/servers/$SERVER/services.output &
+    /usr/bin/ssh $SERVER "/sbin/chkconfig --list" | grep ":on	" | sort > ${ADMIN}/servers/$SERVER/services.output &
     PID=$!
   fi
   if [[ $OS = "SunOS" ]]
   then
-    /usr/bin/ssh $SERVER "/usr/bin/svcs" | grep -v offline | sort > $LOC/servers/$SERVER/services.output &
+    /usr/bin/ssh $SERVER "/usr/bin/svcs" | grep -v offline | sort > ${ADMIN}/servers/$SERVER/services.output &
     PID=$!
   fi
 
