Updated to use the .config file

diff --git a/bin/getsys b/bin/getsys
--- a/bin/getsys
+++ b/bin/getsys
@@ -3,10 +3,27 @@
 # getsys - Retrieve the.import for system files
 # Owner: Carl Schelin
 
-PROGNAME="getsys"
-LOC=/usr/local/admin
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
 
-for i in `grep -v "^#" $LOC/etc/servers`
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! $RUNBY -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
+
+PROGNAME="getsys"
+
+for i in `grep -v "^#" ${ADMIN_DATA}/servers`
 do
   SERVER=`echo $i|cut -f1 -d:`
   OS=`echo $i|cut -f3 -d:`
@@ -14,7 +31,7 @@ do
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${ADMIN}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
@@ -33,7 +50,7 @@ do
     rm $SVRPATH/$CONTENT.import
   fi
 
-  /usr/bin/scp $SERVER:/opt/intrado/etc/$CONTENT.import $SVRPATH 2>&1 &
+  /usr/bin/scp $SERVER:${SCRIPTS_LOGS}/$CONTENT.import $SVRPATH 2>&1 &
   PID=$!
 
 # wait for the specified number of seconds for scp to complete
