updated to use .config

diff --git a/bin/getsudoers b/bin/getsudoers
--- a/bin/getsudoers
+++ b/bin/getsudoers
@@ -3,16 +3,34 @@
 # getsudoers - Retrieve the chksudoers.dat output from all boxes
 # Owner: Carl Schelin
 
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! $RUNBY -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
+
 PROGNAME="getsudoers"
-LOC=/usr/local/admin
-CHECK="$LOC/servers/check.sudoers"
+
+CHECK="${ADMIN}/servers/check.sudoers"
 
 if [[ -f $CHECK ]]
 then
   rm $CHECK
 fi
 
-for i in `grep -v "^#" $LOC/etc/servers`
+for i in `grep -v "^#" ${ADMIN_DATA}/servers`
 do
   SERVER=`echo $i|cut -f1 -d:`
   OS=`echo $i|cut -f3 -d:`
@@ -20,7 +38,7 @@ do
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${ADMIN}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
@@ -44,7 +62,7 @@ do
     rm $SVRPATH/$CONTENT
   fi
 
-  /usr/bin/scp $SERVER:/opt/intrado/etc/$CONTENT $SVRPATH 2>&1 &
+  /usr/bin/scp $SERVER:${SCRIPTS_LOGS}/$CONTENT $SVRPATH 2>&1 &
   PID=$!
 
 # wait for the specified number of seconds for scp to complete
