changed to use the .config file and remove company info

diff --git a/bin/getsudo b/bin/getsudo
--- a/bin/getsudo
+++ b/bin/getsudo
@@ -2,19 +2,36 @@
 
 # getsudo - Retrieve the temp root users
 # Owner: Carl Schelin
-# 8/15/11 - change retrieval directory to /opt/intrado and update timeout to 180 seconds
+# 8/15/11 - change retrieval directory to the scripts directory and update timeout to 180 seconds
+
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
+if [[ ! ${RUNBY} -eq 5000 ]]
+then
+  echo "This script must be run by the Unix Service account."
+  exit 0
+fi
 
 PROGNAME="getsudo"
-LOC=/usr/local/admin
 
-for i in `grep -v "^#" $LOC/etc/servers`
+for i in `grep -v "^#" ${ADMIN_DATA}/servers`
 do
   SERVER=`echo $i|cut -f1 -d:`
 
 # Check to make sure the target directory exists
 # if not, create it and set the perms
 
-  SVRPATH="$LOC/servers/$SERVER"
+  SVRPATH="${ADMIN}/servers/$SERVER"
 
   if [ ! -d $SVRPATH ]
   then
@@ -33,7 +50,7 @@ do
     rm $SVRPATH/$CONTENT.output
   fi
 
-  /usr/bin/scp $SERVER:/opt/intrado/etc/$CONTENT.output $SVRPATH/$CONTENT.output &
+  /usr/bin/scp $SERVER:${SCRIPTS_LOGS}/$CONTENT.output $SVRPATH/$CONTENT.output &
   PID=$!
 
 # wait for the specified number of seconds for scp to complete
