added the missing config load script

diff --git a/bin/putintrado b/bin/putintrado
--- a/bin/putintrado
+++ b/bin/putintrado
@@ -3,6 +3,18 @@
 # putintrado - Update all servers with the current intrado scripts
 # Owner: Carl Schelin
 
+BASENAME=$(basename "$0")
+DIRNAME=$(dirname "$0")
+
+if [[ ! -f ${DIRNAME}/../.config ]]
+then
+  echo "Unable to locate ${DIRNAME}/../.config. Exiting."
+  exit 1
+fi
+
+# Source the configuration file
+. "${DIRNAME}"/../.config
+
 PROGNAME="putintrado"
 
 if [[ ! $RUNBY -eq 5000 ]]
